Oceproject 4852
NCIOCPL/wcms-qa-testing-framework pull request #211
Opened 2018-12-26 15:56 UTC by SupriyaSaxena0605

Please approve the test for OCEPROJECT-4852.
This ticket includes test method 'verifySitewideSearchBottomSearchBar'.

2019-01-02 23:32 UTC, blairlearn commented on src/main/java/gov/nci/commonobjects/SitewideSearch.java
> +		ScrollUtil.scrollIntoview(driver, driver.findElement(By.xpath("(//h4)[2]")));
Please replace xpath with css.

2019-01-02 23:42 UTC, blairlearn commented on src/test/java/gov/nci/CommonObjects/Tests/SitewideSearch_Test.java
> +		search.search(keyword);
Methods on a page object which perform an action should return a new page object.  Assertions are then executed against the returned object.

This test is actually concealing multiple other tests.

* If a search is performed, does the browser move to the expected new URL?
  * The test should check for the expected URL path.
  * The test should also check for the expected URL parameters.
* Load a search results page (use the explicit URL) and check (each of these is a separate test)
  * Does the search results page contain a New Search button?
  * Does the search results page contain a Search within results button?
  * etc.

The tests for the search results page can be parameterized to load multiple URLs from a data file.

2019-01-02 23:42 UTC, blairlearn requested changes
See notes in the conversation view.

2019-01-15 21:32 UTC, SupriyaSaxena0605 commented
Created separate pull requests for individual tickets, therefore closing this one

2019-01-15 21:32 UTC, closed without merging